name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: labo02_db
          MYSQL_USER: labo02
          MYSQL_PASSWORD: labo02
        ports: ["3306:3306"]
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis:7
        ports: ["6379:6379"]
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo02_db" >> .env
          echo "DB_USER=labo02" >> .env
          echo "DB_PASSWORD=labo02" >> .env
          echo "REDIS_HOST=127.0.0.1" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Wait for services
        run: |
          sleep 10
          
      - name: Initialize database
        run: |
          mysql -h 127.0.0.1 -u labo02 -plabo02 labo02_db < db-init/init.sql
          
      - name: Run tests
        run: |
          cd src
          python -m pytest ../src/tests/ -v

  # Déploiement manuel requis - VM non accessible depuis GitHub Actions
  # Pour déployer manuellement :
  # 1. ssh log430@10.194.32.238
  # 2. cd ~/log430-a25-labo2
  # 3. git pull origin main
  # 4. docker compose build
  # 5. docker compose up -d


